/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculo_volumenes;

import javax.swing.JOptionPane;

/**
 *
 * @author jorge
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.Btn_Calcular.setVisible(false);
        this.Caja1.setVisible(false);
        this.Caja2.setVisible(false);
        this.Caja3.setVisible(false);
        this.Txt1.setVisible(false);
        this.Txt2.setVisible(false);
        this.Txt3.setVisible(false);
        this.Caja_Resultado.setVisible(false);
        this.Txt_Resultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cmb_Figura = new javax.swing.JComboBox<>();
        Btn_Aceptar = new javax.swing.JButton();
        Btn_Calcular = new javax.swing.JButton();
        Caja1 = new javax.swing.JTextField();
        Caja2 = new javax.swing.JTextField();
        Caja3 = new javax.swing.JTextField();
        Txt1 = new javax.swing.JLabel();
        Txt2 = new javax.swing.JLabel();
        Txt3 = new javax.swing.JLabel();
        Caja_Resultado = new javax.swing.JTextField();
        Txt_Resultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Calcular Volumen");

        Cmb_Figura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Esfera", "Cubo", "Prisma", " " }));

        Btn_Aceptar.setText("Aceptar");
        Btn_Aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_AceptarMouseClicked(evt);
            }
        });

        Btn_Calcular.setText("Calcular");
        Btn_Calcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_CalcularMouseClicked(evt);
            }
        });

        Txt1.setText("jLabel2");

        Txt2.setText("jLabel3");

        Txt3.setText("jLabel4");

        Txt_Resultado.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(227, 227, 227))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Cmb_Figura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addComponent(Btn_Aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Btn_Calcular)
                                .addComponent(Txt_Resultado))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Caja3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Caja_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cmb_Figura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Aceptar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt1)
                    .addComponent(Txt2)
                    .addComponent(Txt3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caja2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caja3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(Txt_Resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Caja_Resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Calcular)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_AceptarMouseClicked
        // TODO add your handling code here:
        int V1;
        V1 = this.Cmb_Figura.getSelectedIndex();
        //Activacion de componentes graficos necesarios por desicion.
        switch (V1)
        {
            case 0:
                String v1 = "Radio";
                Txt2.setText(v1);
                this.Txt2.setVisible(true);
                this.Caja2.setVisible(true);
                this.Caja_Resultado.setVisible(true);
                this.Btn_Calcular.setVisible(true);
                this.Txt_Resultado.setVisible(true);
                break;
            case 1:
                String v2 = "Área";
                Txt2.setText(v2);
                this.Txt2.setVisible(true);
                this.Caja2.setVisible(true);
                this.Caja_Resultado.setVisible(true);
                this.Btn_Calcular.setVisible(true);
                this.Txt_Resultado.setVisible(true);
                break;
            case 2:
                String V3,V4,V5;
                V3="Área";
                V4="Base";
                V5= "Altura";
                Txt1.setText(V3);
                Txt2.setText(V4);
                Txt3.setText(V5);
                this.Txt1.setVisible(true);
                this.Caja1.setVisible(true);
                this.Txt2.setVisible(true);
                this.Caja2.setVisible(true);
                this.Txt3.setVisible(true);
                this.Caja3.setVisible(true);
                this.Caja_Resultado.setVisible(true);
                this.Btn_Calcular.setVisible(true);
                this.Txt_Resultado.setVisible(true);
                break;
        }
    }//GEN-LAST:event_Btn_AceptarMouseClicked

    private void Btn_CalcularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_CalcularMouseClicked
        // TODO add your handling code here:
        int V1 = this.Cmb_Figura.getSelectedIndex();
        //Desición de cálculo de volumen
        switch (V1)
        {
            case 0:
                Double A1= Double.parseDouble(this.Caja2.getText());
                Double V3 = Calcular.Calvol(A1);
                JOptionPane.showMessageDialog(null,""+V3);
                this.Caja_Resultado.setText(V3.toString());
                break;
            case 1:
                int C1 = Integer.parseInt(this.Caja2.getText());
                Double V4 = Calcular.Calvol(C1);
                JOptionPane.showMessageDialog(null, ""+V4);
                this.Caja_Resultado.setText(V4.toString());
                break;
            case 2:
                Double P1,P2,P3,R;
                P1 = Double.parseDouble(this.Caja1.getText());
                P2 = Double.parseDouble(this.Caja2.getText());
                P3 = Double.parseDouble(this.Caja3.getText());
                R = Calcular.Calvol(P1, P2, P3);
                JOptionPane.showMessageDialog(null,""+R);
                this.Caja_Resultado.setText(R.toString());
                break;
        }
    }//GEN-LAST:event_Btn_CalcularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Aceptar;
    private javax.swing.JButton Btn_Calcular;
    private javax.swing.JTextField Caja1;
    private javax.swing.JTextField Caja2;
    private javax.swing.JTextField Caja3;
    private javax.swing.JTextField Caja_Resultado;
    private javax.swing.JComboBox<String> Cmb_Figura;
    private javax.swing.JLabel Txt1;
    private javax.swing.JLabel Txt2;
    private javax.swing.JLabel Txt3;
    private javax.swing.JLabel Txt_Resultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
